/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCallbackRouteImport } from './routes/api/callback'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiReviseRouteImport } from './routes/api/revise'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCallbackRoute = ApiCallbackRouteImport.update({
  id: '/api/callback',
  path: '/api/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviseRoute = ApiReviseRouteImport.update({
  id: '/api/revise',
  path: '/api/revise',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/revise': typeof ApiReviseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/revise': typeof ApiReviseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/callback': typeof ApiCallbackRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/revise': typeof ApiReviseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/callback' | '/api/generate' | '/api/revise'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/callback' | '/api/generate' | '/api/revise'
  id: '__root__' | '/' | '/api/callback' | '/api/generate' | '/api/revise'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCallbackRoute: typeof ApiCallbackRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiReviseRoute: typeof ApiReviseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/callback': {
      id: '/api/callback'
      path: '/api/callback'
      fullPath: '/api/callback'
      preLoaderRoute: typeof ApiCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/revise': {
      id: '/api/revise'
      path: '/api/revise'
      fullPath: '/api/revise'
      preLoaderRoute: typeof ApiReviseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCallbackRoute: ApiCallbackRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiReviseRoute: ApiReviseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
